export const NAVIGATE = {
	HOME: "/home",
	MY_PAGE: "/my-page",
	BOOST: "/boost",
	// boostDetail: (id: string) => `/boost/${encodeURIComponent(id)}`,
	boostDetail: `/boost/{id}`,
	boostParticipate: `/boost/{id}/participate`,
	DISCOVERY: "/discovery",
	SUBMIT_TRACK: "/discovery/submit-track",
	SUBMIT_TRACK_SUCCESS: "/discovery/submit-track/success",
	SUBMIT_TRACK_ERROR: "/discovery/submit-track/error",
	MY_SUBMISSIONS: "/discovery/my-submission",
	VOTE_TRACK: `/discovery/{id}/vote-track`,
	TRACK: `/discovery/track/{id}`,
};
