import type { Metadata } from "next";
import { allerta, averta, inter } from "@/share/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${allerta.variable} ${averta.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
